### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Jessol90** [jensb89/Netflix-to-Trakt-Import#37]
Hi,

First of all thanks for this! I've followed all the steps and changed my CSV. Because it was in Dutch (my country), even did a search for special characters and changed it. But i'm getting this type error and I can't seem to fix the problem. Good to know that i'm working from terminal at my macOS Ventura.

Traceback (most recent call last):
  File "/Users/myname/Documents/Netflix-to-Trakt-Import-master/netflix2trakt.py", line 46, in <module>
    netflixHistory.addEntry(entry, watchedAt)
  File "/Users/myname/Documents/Netflix-to-Trakt-Import-master/NetflixTvShow.py", line 69, in addEntry
    self.addTvShowEntry(showName, seasonNumber, episodeTitle, entryDate)
  File "/Users/myname/Documents/Netflix-to-Trakt-Import-master/NetflixTvShow.py", line 140, in addTvShowEntry
    episode.addWatchedDate(watchedDate)
  File "/Users/myname/Documents/Netflix-to-Trakt-Import-master/NetflixTvShow.py", line 215, in addWatchedDate
    time = datetime.datetime.strptime(watcheddate + "20:15", config.CSV_DATETIME_FORMAT + "%h:%m:%s")
                                      ~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by jensb89** [comment]
Hi, 
sorry for the late reply, I don't have so much time for Github lately. 
Have you already solved this error? 
The error suggests that either "watcheddate" or "config.CSV_DATETIME_FORMAT" is not defined, both of which should not happen.

It's hard to help from just the error, so 2 questions if it is not solved yet:

1. Is the CSV_DATEIMTE_FORMAT specified in the config.py and does it match the format in your csv?
2. Can you see from the print outputs or the log at which episode/movie the error occurs? That might help to reproduce it and narrow it down. Or if you could upload a part of your csv that would be helpful as well.

**Comment by kev-conway** [comment]
Hey @jensb89 - I'm having the same problem. I get the same "unsupported operand type(s) for +: 'NoneType' and 'str'" also on line 215.

I even tried running it with just one entry to see if it was maybe a bad entry causing the error.
This is the file I used for testing - [NetflixViewingHistory.csv](https://github.com/jensb89/Netflix-to-Trakt-Import/files/12062645/NetflixViewingHistory.csv)

In my config.py file: CSV_DATETIME_FORMAT = "%d.%m.%Y"
(the date is correct because I had it wrong at first and I was getting a "date format is wrong" error but saw where I went wrong and fixed that).

When I run it and get the error, the Netflix2TraktImportLog.log file is empty.

**Comment by jensb89** [comment]
@kev-conway  Thanks, that was super helpful. The error is actually that the delimiter in the csv file is different and that way the entry and date is not parsed correctly. Super strange the the netflix export is so different in different countries :D
 
Anyway, the "csvReader" module doesn't seem to automatically detect the ";". My export history and the ones of most other users used "," as a delimiter. I will add it as a option to the config
